# Generated by Django 3.1 on 2020-08-18 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Life',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='life/images/')),
                ('url', models.URLField(blank=True)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
