# Generated by Django 3.1 on 2020-08-17 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myblog',
            name='image',
        ),
        migrations.RemoveField(
            model_name='myblog',
            name='url',
        ),
        migrations.AddField(
            model_name='myblog',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='myblog',
            name='description',
            field=models.TextField(),
        ),
    ]
