# Generated by Django 3.1 on 2020-10-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockscreener', '0002_auto_20201029_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
