# Generated by Django 3.1 on 2020-10-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockscreener', '0003_auto_20201030_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ma20', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ma60', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ma120', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'stock_price_history',
            },
        ),
        migrations.RenameField(
            model_name='stockprice',
            old_name='price',
            new_name='close',
        ),
        migrations.AddField(
            model_name='stockprice',
            name='high',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockprice',
            name='low',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockprice',
            name='name',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockprice',
            name='open',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='stockprice',
            unique_together={('ticker', 'name')},
        ),
        migrations.AlterModelTable(
            name='stockprice',
            table='stock_price_last_day',
        ),
    ]
