# Generated by Django 3.1 on 2020-11-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockscreener', '0004_auto_20201030_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpricehistory',
            name='close',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockpricehistory',
            name='ma120',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockpricehistory',
            name='ma20',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockpricehistory',
            name='ma60',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockpricehistory',
            name='name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='stockpricehistory',
            name='ticker',
            field=models.CharField(default='None', max_length=4),
        ),
    ]
